# python -m pip install --upgrade pip
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install obsidian-html
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/krissrex/obsidian-html.git
    
    - name: Generate HTML through obsidian-html
      run: obsidian-html ./vault -o ./out -t ./template.html -d daily
    
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: out
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
